spark-particles: true
max-spawns-per-tick: 4

spawners:
  iron_golem_spawner:
    material: SPAWNER
    display-name: "<gold>Iron Golem Spawner"
    lore:
      - "<gray>Place this spawner to"
      - "<gray>spawn Iron Golems"
    entity-type: IRON_GOLEM
    delay: 200
    required-player-range: 16
    min-radius: 0
    max-radius: 0
    min-amount: 1
    max-amount: 1

  zombie_spawner:
    material: SPAWNER
    display-name: "<red>Zombie Spawner"
    lore:
      - "<gray>Place this spawner to"
      - "<gray>spawn Zombies"
    entity-type: ZOMBIE
    delay: 200
    required-player-range: 16
    min-radius: 0
    max-radius: 0
    min-amount: 1
    max-amount: 1

  skeleton_spawner:
    material: SPAWNER
    display-name: "<white>Skeleton Spawner"
    lore:
      - "<gray>Place this spawner to"
      - "<gray>spawn Skeletons"
    entity-type: SKELETON
    delay: 200
    required-player-range: 16
    min-radius: 0
    max-radius: 0
    min-amount: 1
    max-amount: 1

  elephant_spawner:
    material: SPAWNER
    display-name: "<gold>Elephant Spawner"
    lore:
      - "<gray>Place this spawner to"
      - "<gray>spawn Elephants"
    entity-type: "mm:elephant"
    delay: 200
    required-player-range: 16
    min-radius: 1
    max-radius: 5
    min-amount: 1
    max-amount: 3
