spark-particles: true
max-spawns-per-tick: 4

spawners:
  iron_golem_spawner:
    material: SPAWNER
    display-name: "<gold>Spawner de Golem de Fer"
    lore:
      - "<gray>Place ce spawner pour"
      - "<gray>faire apparaître des Golems de Fer"
    entity-type: IRON_GOLEM
    delay: 200
    required-player-range: 16
    min-radius: 0
    max-radius: 0
    min-amount: 1
    max-amount: 1

  zombie_spawner:
    material: SPAWNER
    display-name: "<red>Spawner de Zombie"
    lore:
      - "<gray>Place ce spawner pour"
      - "<gray>faire apparaître des Zombies"
    entity-type: ZOMBIE
    delay: 200
    required-player-range: 16
    min-radius: 0
    max-radius: 0
    min-amount: 1
    max-amount: 1

  skeleton_spawner:
    material: SPAWNER
    display-name: "<white>Spawner de Squelette"
    lore:
      - "<gray>Place ce spawner pour"
      - "<gray>faire apparaître des Squelettes"
    entity-type: SKELETON
    delay: 200
    required-player-range: 16
    min-radius: 0
    max-radius: 0
    min-amount: 1
    max-amount: 1

  elephant_spawner:
    material: SPAWNER
    display-name: "<gold>Spawner de éléphant"
    lore:
      - "<gray>Place ce spawner pour"
      - "<gray>faire apparaître des éléphants"
    entity-type: "mm:elephant"
    delay: 200
    required-player-range: 16
    min-radius: 1
    max-radius: 5
    min-amount: 1
    max-amount: 3
